name: kodiary_test_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  riverpod_dev_infinite_scroll: ^2.0.0-dev.5
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6

  google_maps_flutter: ^2.2.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
     - assets/json/form.json
